# Generated by Django 5.1.7 on 2025-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=1000)),
                ('responsible_person', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=1000)),
                ('webpage', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('profile_pic', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('pdf', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
