# Generated by Django 5.1.7 on 2025-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_a', '0002_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='static/profile_images/'),
        ),
    ]
