# Generated by Django 5.2.5 on 2026-02-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biz_a', '0006_otpverification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='static/organization_pdfs/')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='Biz_a.organization')),
            ],
            options={
                'db_table': 'organization_pdfs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
