from django.db import models 
class Organization(models.Model):
    org_name = models.CharField(max_length=1000)
    responsible_person = models.CharField(max_length=1000,null=True,blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=1000,null=True,blank=True)
    webpage = models.CharField(max_length=1000,null=True,blank=True)
    linkedin = models.CharField(max_length=1000,null=True,blank=True)
    profile_pic = models.FileField(null=True,blank=True,upload_to='static/profile_images/')
    company_banner = models.FileField(null=True,blank=True,upload_to='static/company_banners/')
    company_logo = models.FileField(null=True,blank=True,upload_to='static/company_logos/')
    short_description = models.TextField(null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    active = models.BooleanField(default=False)
    iiealra_index_id = models.CharField(max_length=1000,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
